apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: app-helm
  namespace: kluctl-system
spec:
  source:
    url: https://github.com/guillemtp/kluctl-app-helm-chart.git
    ref: {{ appHelm.version | to_json }}
  interval: 1m
  timeout: 6m


  args:
    app_example_param: {{ appHelm.app_example_param }}
    global_example_param: {{ global_example_param }}

  target: {{ target.name }}

  delete: true
  prune: true

